apiVersion: v1
kind: Service
metadata:
  name: cf-test-postgres-service
  labels:
    name: cf-test-postgres-service
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    name: cf-test-postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cf-test-postgres
spec:
  replicas: 1
  template:
    metadata:
      name: cf-test-postgres
      labels:
        name: cf-test-postgres
    spec:
      containers:
      - name: cf-test-postgres
        image: zreigz/cf-test-postgres
        ports:
        - containerPort: 8080

